import math
from nugui.generators.base import CodeGenerator
from nugui.models.elements import StateNode, TransitionLine


class SystemVerilogGenerator(CodeGenerator):
    def generate(self) -> str:
        code = []

        # 1. Header & Module
        code.append(f"// Generated by abVisualRTL")
        code.append(f"module {self.settings.project_name} (")

        # Ports
        ports_code = []
        # Add Clock/Reset automatically
        ports_code.append(f"{self.indent(1)}input logic {self.settings.clock_name}")
        ports_code.append(f"{self.indent(1)}input logic {self.settings.reset_name}")

        # Add User Ports
        for port in self.settings.ports:
            ports_code.append(f"{self.indent(1)}{port.get_sv_decl()}")

        code.append(",\n".join(ports_code))
        code.append(");")
        code.append("")

        # 2. State Enumeration
        if not self.nodes:
            code.append(f"{self.indent(1)}// No states defined")
            code.append("endmodule")
            return "\n".join(code)

        state_names = [node.name for node in self.nodes.values()]
        # Calculate bit width needed
        num_states = len(state_names)
        width = math.ceil(math.log2(num_states)) if num_states > 1 else 1

        code.append(f"{self.indent(1)}// State Encoding")
        code.append(f"{self.indent(1)}typedef enum logic [{width - 1}:0] {{")
        code.append(f"{self.indent(2)}" + ", ".join(state_names))
        code.append(f"{self.indent(1)}}} state_t;")
        code.append("")
        code.append(f"{self.indent(1)}state_t state_reg, state_next;")
        code.append("")

        # 3. Sequential Logic (Reset Handler)
        rst_edge = "posedge"  # Default async high
        rst_logic = f"if ({self.settings.reset_name})"

        if self.settings.reset_active_low:
            rst_edge = "negedge"
            rst_logic = f"if (!{self.settings.reset_name})"

        sensitivity = f"posedge {self.settings.clock_name}"
        if not self.settings.is_synchronous_reset:
            sensitivity += f" or {rst_edge} {self.settings.reset_name}"

        # Find Reset State (First created or explicitly marked)
        reset_node = next((n for n in self.nodes.values() if n.is_reset_state), list(self.nodes.values())[0])

        code.append(f"{self.indent(1)}// Sequential State Register")
        code.append(f"{self.indent(1)}always_ff @({sensitivity}) begin")
        code.append(f"{self.indent(2)}{rst_logic}")
        code.append(f"{self.indent(3)}state_reg <= {reset_node.name};")
        code.append(f"{self.indent(2)}else")
        code.append(f"{self.indent(3)}state_reg <= state_next;")
        code.append(f"{self.indent(1)}end")
        code.append("")

        # 4. Next State Logic
        code.append(f"{self.indent(1)}// Next State Logic")
        code.append(f"{self.indent(1)}always_comb begin")
        code.append(f"{self.indent(2)}state_next = state_reg;")
        code.append("")
        code.append(f"{self.indent(2)}case (state_reg)")

        for node in self.nodes.values():
            code.append(f"{self.indent(3)}{node.name}: begin")

            # Moore Actions (State actions)
            if node.actions:
                for action in node.actions:
                    # Sanitize: ensure semicolon
                    act = action.strip()
                    if act and not act.endswith(';'): act += ";"
                    code.append(f"{self.indent(4)}{act}")

            # Transitions
            # Group lines starting from this node
            outgoing = [line for line in self.lines if line.start_state_id == node.id]
            # Sort by Priority (1 is highest, so ascending sort)
            outgoing.sort(key=lambda x: x.priority)

            if outgoing:
                for i, line in enumerate(outgoing):
                    target_name = self.nodes[line.end_state_id].name

                    # Sanitize Condition: Handle empty strings
                    cond = line.condition.strip()
                    if not cond: cond = "1"

                    # Sanitize Action: Ensure semicolon
                    line_act = line.action.strip()
                    if line_act and not line_act.endswith(';'): line_act += ";"

                    # Scenario 1: Single Unconditional Transition (No if/else needed)
                    if len(outgoing) == 1 and cond == "1":
                        code.append(f"{self.indent(4)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(4)}{line_act}")
                        continue

                    # Scenario 2: Start of If/Else chain
                    if i == 0:
                        code.append(f"{self.indent(4)}if ({cond}) begin")
                        code.append(f"{self.indent(5)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(5)}{line_act}")
                        code.append(f"{self.indent(4)}end")

                    # Scenario 3: Subsequent branches
                    else:
                        # If condition is "1" or "else", treat as the final 'else' block
                        if cond == "1" or cond.lower() == "else":
                            code.append(f"{self.indent(4)}else begin")
                        else:
                            code.append(f"{self.indent(4)}else if ({cond}) begin")

                        code.append(f"{self.indent(5)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(5)}{line_act}")
                        code.append(f"{self.indent(4)}end")

            code.append(f"{self.indent(3)}end")

        code.append(f"{self.indent(2)}endcase")
        code.append(f"{self.indent(1)}end")
        code.append("endmodule")

        return "\n".join(code)
