import re
from nugui.generators.base import CodeGenerator


class SystemVerilogGenerator(CodeGenerator):

    # FIX 2.1: format a port's default_value as an SV literal.
    def _sv_default(self, port) -> str:
        val = (port.default_value or "0").strip()
        if val.isdigit():
            return f"{port.width}'d{val}" if port.width > 1 else f"1'b{val}"
        return val  # user supplied a full literal/expression; emit verbatim

    # FIX 2.2: inside always_comb, assignments must be blocking (=).
    # Users often type non-blocking (led <= '1'), which simulates wrong.
    # Only the assignment operator is rewritten: the pattern requires the
    # line to START with a plain signal target, so a comparison like
    # 'if (a <= b)' is never touched.
    _ASSIGN_RE = re.compile(r"^(\s*[A-Za-z_]\w*\s*(?:\[[^\]]*\]\s*)?)<=")

    def _normalize_action(self, act: str) -> str:
        return self._ASSIGN_RE.sub(r"\1= ", act).replace("=  ", "= ")

    def generate(self) -> str:
        self.check_names()  # FIX 2.3/2.4
        code = []

        # 1. Header & Module
        code.append(f"// Generated by abVisualRTL")
        code.append(f"module {self.settings.project_name} (")

        # Ports
        ports_code = []
        # Add Clock/Reset automatically
        ports_code.append(f"{self.indent(1)}input logic {self.settings.clock_name}")
        ports_code.append(f"{self.indent(1)}input logic {self.settings.reset_name}")

        # Add User Ports
        for port in self.settings.ports:
            ports_code.append(f"{self.indent(1)}{port.get_sv_decl()}")

        code.append(",\n".join(ports_code))
        code.append(");")
        code.append("")

        # 2. State Enumeration
        if not self.nodes:
            code.append(f"{self.indent(1)}// No states defined")
            code.append("endmodule")
            return "\n".join(code)

        state_names = [node.name for node in self.nodes.values()]
        # Calculate bit width needed
        num_states = len(state_names)
        # FIX 2.5: exact integer computation - float log2 can land just
        # under an integer at exact powers of two on some platforms.
        width = max(1, (num_states - 1).bit_length())

        code.append(f"{self.indent(1)}// State Encoding")
        code.append(f"{self.indent(1)}typedef enum logic [{width - 1}:0] {{")
        code.append(f"{self.indent(2)}" + ", ".join(state_names))
        code.append(f"{self.indent(1)}}} state_t;")
        code.append("")
        code.append(f"{self.indent(1)}state_t state_reg, state_next;")
        code.append("")

        # 3. Sequential Logic (Reset Handler)
        rst_edge = "posedge"  # Default async high
        rst_logic = f"if ({self.settings.reset_name})"

        if self.settings.reset_active_low:
            rst_edge = "negedge"
            rst_logic = f"if (!{self.settings.reset_name})"

        sensitivity = f"posedge {self.settings.clock_name}"
        if not self.settings.is_synchronous_reset:
            sensitivity += f" or {rst_edge} {self.settings.reset_name}"

        # Find Reset State (First created or explicitly marked)
        reset_node = self.find_reset_node()  # FIX 3.2

        code.append(f"{self.indent(1)}// Sequential State Register")
        code.append(f"{self.indent(1)}always_ff @({sensitivity}) begin")
        code.append(f"{self.indent(2)}{rst_logic}")
        code.append(f"{self.indent(3)}state_reg <= {reset_node.name};")
        code.append(f"{self.indent(2)}else")
        code.append(f"{self.indent(3)}state_reg <= state_next;")
        code.append(f"{self.indent(1)}end")
        code.append("")

        # 4. Next State Logic
        code.append(f"{self.indent(1)}// Next State Logic")
        code.append(f"{self.indent(1)}always_comb begin")
        code.append(f"{self.indent(2)}state_next = state_reg;")

        # FIX 2.1: assign every output its default value at the top of the
        # combinational block so an output driven in only some states or
        # branches cannot infer a latch.
        output_ports = self.output_ports()  # FIX 3.2
        if output_ports:
            code.append(f"{self.indent(2)}// Default outputs (latch prevention)")
            for port in output_ports:
                code.append(f"{self.indent(2)}{port.name} = {self._sv_default(port)};")

        code.append("")
        code.append(f"{self.indent(2)}case (state_reg)")

        for node in self.nodes.values():
            code.append(f"{self.indent(3)}{node.name}: begin")

            # Moore Actions (State actions)
            if node.actions:
                for action in node.actions:
                    # FIX 3.2 + 2.2: shared sanitizer, blocking assignment
                    act = self.clean_action(self._normalize_action(action))
                    code.append(f"{self.indent(4)}{act}")

            # Transitions, highest priority first (FIX 3.2)
            outgoing = self.outgoing_sorted(node)

            if outgoing:
                for i, line in enumerate(outgoing):
                    target_name = self.nodes[line.end_state_id].name

                    # FIX 3.2: shared sanitizers
                    cond = self.clean_condition(line.condition)
                    line_act = self.clean_action(self._normalize_action(line.action))

                    # Scenario 1: Single Unconditional Transition (No if/else needed)
                    if len(outgoing) == 1 and cond == "1":
                        code.append(f"{self.indent(4)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(4)}{line_act}")
                        continue

                    # Scenario 2: Start of If/Else chain
                    if i == 0:
                        code.append(f"{self.indent(4)}if ({cond}) begin")
                        code.append(f"{self.indent(5)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(5)}{line_act}")
                        code.append(f"{self.indent(4)}end")

                    # Scenario 3: Subsequent branches
                    else:
                        # If condition is "1" or "else", treat as the final 'else' block
                        if cond == "1" or cond.lower() == "else":
                            code.append(f"{self.indent(4)}else begin")
                        else:
                            code.append(f"{self.indent(4)}else if ({cond}) begin")

                        code.append(f"{self.indent(5)}state_next = {target_name};")
                        if line_act: code.append(f"{self.indent(5)}{line_act}")
                        code.append(f"{self.indent(4)}end")

            code.append(f"{self.indent(3)}end")

        code.append(f"{self.indent(2)}endcase")
        code.append(f"{self.indent(1)}end")
        code.append("endmodule")

        return "\n".join(code)
