from nugui.generators.base import CodeGenerator


class VHDLGenerator(CodeGenerator):

    # FIX 2.1: format a port's default_value as a VHDL literal.
    def _vhdl_default(self, port) -> str:
        val = (port.default_value or "0").strip()
        if val in ("0", "1"):
            if port.width > 1:
                return f"(others => '{val}')"
            return f"'{val}'"
        return val  # user supplied a full literal/expression; emit verbatim

    def generate(self) -> str:
        self.check_names()  # FIX 2.3/2.4
        code = []
        name = self.settings.project_name

        # 1. Library & Use Clauses
        code.append("-- Generated by abVisualRTL")
        code.append("library ieee;")
        code.append("use ieee.std_logic_1164.all;")
        code.append("use ieee.numeric_std.all;")
        code.append("")

        # 2. Entity Declaration
        code.append(f"entity {name} is")
        code.append(f"{self.indent(1)}port (")

        ports_code = []
        # Clock and Reset
        ports_code.append(f"{self.indent(2)}{self.settings.clock_name} : in std_logic")
        ports_code.append(f"{self.indent(2)}{self.settings.reset_name} : in std_logic")

        # User Ports
        for port in self.settings.ports:
            ports_code.append(f"{self.indent(2)}{port.get_vhdl_decl()}")

        code.append(";\n".join(ports_code))
        code.append(f"{self.indent(1)});")
        code.append(f"end entity {name};")
        code.append("")

        # 3. Architecture
        code.append(f"architecture rtl of {name} is")
        code.append("")

        # State Type Definition
        if not self.nodes:
            code.append(f"{self.indent(1)}-- No states defined")
            code.append("begin")
            code.append("end architecture;")
            return "\n".join(code)

        state_names = [node.name for node in self.nodes.values()]
        # VHDL Enum type
        code.append(f"{self.indent(1)}type state_type is ({', '.join(state_names)});")
        code.append(f"{self.indent(1)}signal state_reg, state_next : state_type;")
        code.append("")

        code.append("begin")
        code.append("")

        # 4. Sequential Process (Register)
        # Determine Reset Logic
        rst_level = "'0'" if self.settings.reset_active_low else "'1'"
        reset_node = self.find_reset_node()  # FIX 3.2

        code.append(f"{self.indent(1)}-- Sequential State Register")
        code.append(f"{self.indent(1)}process({self.settings.clock_name}, {self.settings.reset_name})")
        code.append(f"{self.indent(1)}begin")

        # Async Reset
        if not self.settings.is_synchronous_reset:
            code.append(f"{self.indent(2)}if {self.settings.reset_name} = {rst_level} then")
            code.append(f"{self.indent(3)}state_reg <= {reset_node.name};")
            code.append(f"{self.indent(2)}elsif rising_edge({self.settings.clock_name}) then")
            code.append(f"{self.indent(3)}state_reg <= state_next;")
            code.append(f"{self.indent(2)}end if;")
        else:
            # Sync Reset
            code.append(f"{self.indent(2)}if rising_edge({self.settings.clock_name}) then")
            code.append(f"{self.indent(3)}if {self.settings.reset_name} = {rst_level} then")
            code.append(f"{self.indent(4)}state_reg <= {reset_node.name};")
            code.append(f"{self.indent(3)}else")
            code.append(f"{self.indent(4)}state_reg <= state_next;")
            code.append(f"{self.indent(3)}end if;")
            code.append(f"{self.indent(2)}end if;")

        code.append(f"{self.indent(1)}end process;")
        code.append("")

        # 5. Combinational Process (Next State Logic)
        # FIX 1.2: build the sensitivity list first, then join once —
        # no trailing comma when there are no input ports.
        sens_list = ["state_reg"] + [p.name for p in self.input_ports()]
        code.append(f"{self.indent(1)}-- Next State Logic")
        code.append(f"{self.indent(1)}process({', '.join(sens_list)})")
        code.append(f"{self.indent(1)}begin")
        code.append(f"{self.indent(2)}state_next <= state_reg;")  # Prevent latch

        # FIX 2.1: assign every output its default value at the top of the
        # combinational process so an output driven in only some states or
        # branches cannot infer a latch.
        output_ports = self.output_ports()  # FIX 3.2
        if output_ports:
            code.append(f"{self.indent(2)}-- Default outputs (latch prevention)")
            for port in output_ports:
                code.append(f"{self.indent(2)}{port.name} <= {self._vhdl_default(port)};")

        code.append("")
        code.append(f"{self.indent(2)}case state_reg is")

        for node in self.nodes.values():
            code.append(f"{self.indent(3)}when {node.name} =>")

            # Moore Actions
            if node.actions:
                for action in node.actions:
                    act = self.clean_action(action)  # FIX 3.2
                    code.append(f"{self.indent(4)}{act}")

            # Transitions, highest priority first (FIX 3.2)
            outgoing = self.outgoing_sorted(node)

            # FIX 1.3: track whether an 'if' has been opened with one boolean
            # instead of re-deriving it from condition strings. This prevents
            # a dangling 'else' when the first transition is unconditional,
            # and guarantees 'end if;' is emitted iff an 'if' was opened.
            opened_if = False
            for line in outgoing:
                target_name = self.nodes[line.end_state_id].name

                cond = self.clean_condition(line.condition)  # FIX 3.2
                # 'if 1 then' is invalid VHDL; normalize to boolean literal
                if cond == "1": cond = "true"

                line_act = self.clean_action(line.action)  # FIX 3.2

                if cond.lower() in ("true", "else"):
                    if opened_if:
                        # Unconditional fallback branch of an open chain
                        code.append(f"{self.indent(4)}else")
                        code.append(f"{self.indent(5)}state_next <= {target_name};")
                        if line_act: code.append(f"{self.indent(5)}{line_act}")
                    else:
                        # Unconditional first branch: emit directly, no if chain
                        code.append(f"{self.indent(4)}state_next <= {target_name};")
                        if line_act: code.append(f"{self.indent(4)}{line_act}")
                    # Anything after an unconditional branch is unreachable
                    break
                else:
                    prefix = "elsif" if opened_if else "if"
                    code.append(f"{self.indent(4)}{prefix} {cond} then")
                    opened_if = True
                    code.append(f"{self.indent(5)}state_next <= {target_name};")
                    if line_act: code.append(f"{self.indent(5)}{line_act}")

            if opened_if:
                code.append(f"{self.indent(4)}end if;")

            code.append("")  # Spacer

        code.append(f"{self.indent(2)}end case;")
        code.append(f"{self.indent(1)}end process;")
        code.append("")
        code.append("end architecture;")

        return "\n".join(code)
