import math
from nugui.generators.base import CodeGenerator
from nugui.models.elements import StateNode, TransitionLine


class VHDLGenerator(CodeGenerator):
    def generate(self) -> str:
        code = []
        name = self.settings.project_name

        # 1. Library & Use Clauses
        code.append("-- Generated by abVisualRTL")
        code.append("library ieee;")
        code.append("use ieee.std_logic_1164.all;")
        code.append("use ieee.numeric_std.all;")
        code.append("")

        # 2. Entity Declaration
        code.append(f"entity {name} is")
        code.append(f"{self.indent(1)}port (")

        ports_code = []
        # Clock and Reset
        ports_code.append(f"{self.indent(2)}{self.settings.clock_name} : in std_logic")
        ports_code.append(f"{self.indent(2)}{self.settings.reset_name} : in std_logic")

        # User Ports
        for port in self.settings.ports:
            ports_code.append(f"{self.indent(2)}{port.get_vhdl_decl()}")

        code.append(";\n".join(ports_code))
        code.append(f"{self.indent(1)});")
        code.append(f"end entity {name};")
        code.append("")

        # 3. Architecture
        code.append(f"architecture rtl of {name} is")
        code.append("")

        # State Type Definition
        if not self.nodes:
            code.append(f"{self.indent(1)}-- No states defined")
            code.append("begin")
            code.append("end architecture;")
            return "\n".join(code)

        state_names = [node.name for node in self.nodes.values()]
        # VHDL Enum type
        code.append(f"{self.indent(1)}type state_type is ({', '.join(state_names)});")
        code.append(f"{self.indent(1)}signal state_reg, state_next : state_type;")
        code.append("")

        code.append("begin")
        code.append("")

        # 4. Sequential Process (Register)
        # Determine Reset Logic
        rst_level = "'0'" if self.settings.reset_active_low else "'1'"
        reset_node = next((n for n in self.nodes.values() if n.is_reset_state), list(self.nodes.values())[0])

        code.append(f"{self.indent(1)}-- Sequential State Register")
        code.append(f"{self.indent(1)}process({self.settings.clock_name}, {self.settings.reset_name})")
        code.append(f"{self.indent(1)}begin")

        # Async Reset
        if not self.settings.is_synchronous_reset:
            code.append(f"{self.indent(2)}if {self.settings.reset_name} = {rst_level} then")
            code.append(f"{self.indent(3)}state_reg <= {reset_node.name};")
            code.append(f"{self.indent(2)}elsif rising_edge({self.settings.clock_name}) then")
            code.append(f"{self.indent(3)}state_reg <= state_next;")
            code.append(f"{self.indent(2)}end if;")
        else:
            # Sync Reset
            code.append(f"{self.indent(2)}if rising_edge({self.settings.clock_name}) then")
            code.append(f"{self.indent(3)}if {self.settings.reset_name} = {rst_level} then")
            code.append(f"{self.indent(4)}state_reg <= {reset_node.name};")
            code.append(f"{self.indent(3)}else")
            code.append(f"{self.indent(4)}state_reg <= state_next;")
            code.append(f"{self.indent(3)}end if;")
            code.append(f"{self.indent(2)}end if;")

        code.append(f"{self.indent(1)}end process;")
        code.append("")

        # 5. Combinational Process (Next State Logic)
        code.append(f"{self.indent(1)}-- Next State Logic")
        code.append(
            f"{self.indent(1)}process(state_reg, {', '.join([p.name for p in self.settings.ports if p.direction.value == 'input'])})")
        code.append(f"{self.indent(1)}begin")
        code.append(f"{self.indent(2)}state_next <= state_reg;")  # Prevent latch
        code.append("")
        code.append(f"{self.indent(2)}case state_reg is")

        for node in self.nodes.values():
            code.append(f"{self.indent(3)}when {node.name} =>")

            # Moore Actions
            if node.actions:
                for action in node.actions:
                    act = action.strip()
                    if act and not act.endswith(';'): act += ";"
                    code.append(f"{self.indent(4)}{act}")

            # Transitions
            outgoing = [line for line in self.lines if line.start_state_id == node.id]
            outgoing.sort(key=lambda x: x.priority)

            if outgoing:
                first = True
                for line in outgoing:
                    prefix = "if" if first else "elsif"
                    target_name = self.nodes[line.end_state_id].name

                    cond = line.condition.strip()
                    if not cond: cond = "1"  # VHDL usually uses '1' for true in std_logic, or 'true' boolean

                    # Convert "1" to "true" for VHDL if statements usually require boolean context
                    # or simplistic checking. Assuming user types HDL condition.
                    # Special check: if user typed "1", in VHDL 'if 1 then' is invalid.
                    if cond == "1": cond = "true"

                    line_act = line.action.strip()
                    if line_act and not line_act.endswith(';'): line_act += ";"

                    # Scenario 1: Unconditional (Single)
                    if len(outgoing) == 1 and cond.lower() == "true":
                        code.append(f"{self.indent(4)}state_next <= {target_name};")
                        if line_act: code.append(f"{self.indent(4)}{line_act}")
                        continue

                    # Scenario 2: If/Elsif
                    if cond.lower() == "true" or cond.lower() == "else":
                        code.append(f"{self.indent(4)}else")
                    else:
                        code.append(f"{self.indent(4)}{prefix} {cond} then")

                    code.append(f"{self.indent(5)}state_next <= {target_name};")
                    if line_act: code.append(f"{self.indent(5)}{line_act}")

                    # Close the if block only after processing all lines?
                    # No, we need to track logic structure.
                    # Unlike SV, VHDL is verbose. We need 'end if;' at the very end of the chain.
                    first = False

                # Close the chain
                if not (len(outgoing) == 1 and outgoing[0].condition.strip() in ["1", ""]):
                    code.append(f"{self.indent(4)}end if;")

            code.append("")  # Spacer

        code.append(f"{self.indent(2)}end case;")
        code.append(f"{self.indent(1)}end process;")
        code.append("")
        code.append("end architecture;")

        return "\n".join(code)
